[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "polywrap-uri-resolvers"
version = "0.1.0"
description = ""
authors = ["Cesar <cesar@polywrap.io>", "Niraj <niraj@polywrap.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wasmtime = "^1.0.1"
result = "^0.8.0"
polywrap-core = { path = "../polywrap-core", develop = true }
polywrap-wasm = { path = "../polywrap-wasm", develop = true }

[tool.poetry.dev-dependencies]
bandit = "1.7.4"
black = "22.6.0"
flake8 = "5.0.4"
mypy = "0.971"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"

[tool.bandit]
# default

[tool.black]
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
allow_redefinition = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = true
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
strict = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
  "tests"
]