name: CD
on:
  push:
    branches:
      - main
  # When Pull Request is merged
  # pull_request_target:
  #   types: [closed]

jobs:
  GetVersion:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      version: ${{ env.RELEASE_VERSION }}
    # if: |
    #   github.event.pull_request.user.login == 'polywrap-build-bot' &&
    #   github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Halt release if CI failed
      #   run: exit 1
      #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      - name: Read VERSION into env.RELEASE_VERSION
        run: echo RELEASE_VERSION=$(cat VERSION) >> $GITHUB_ENV
      - name: Check if tag Exists
        id: tag_check
        shell: bash -ex {0}
        run: |
          GET_API_URL="https://api.github.com/repos/${{github.repository}}/git/ref/tags/${{env.RELEASE_VERSION}}"
          http_status_code=$(curl -LI $GET_API_URL -o /dev/null -w '%{http_code}\n' -s \
            -H "Authorization: token ${GITHUB_TOKEN}")
          if [ "$http_status_code" -ne "404" ] ; then
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Github-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - GetVersion
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print version with needs
        run: echo ${{ needs.GetVersion.outputs.version }}
      - id: changelog
        name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          unreleasedOnly: true
          unreleasedLabel: ${{ needs.GetVersion.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.GetVersion.outputs.version }}
          release_name: Release ${{ needs.GetVersion.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: false

  Dev-PR:
    needs:
      - GetVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.name '${{env.BUILD_BOT}}'
          git config --global user.email '${{env.BUILD_BOT}}@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.POLYWRAP_BUILD_BOT_PAT }}

      - name: Merge main into dev
        run: git merge origin/main

      - name: set env.RELEASE_FORKS to Release Forks' Organization
        run: echo RELEASE_FORKS=polywrap-release-forks >> $GITHUB_ENV

      - name: Set env.BUILD_BOT to Build Bot's Username
        run: echo BUILD_BOT=polywrap-build-bot >> $GITHUB_ENV

      - name: Read VERSION into env.RELEASE_VERSION
        run: echo RELEASE_VERSION=$(cat VERSION) >> $GITHUB_ENV

      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      # - name: Install poetry
      #   run: curl -sSL https://install.python-poetry.org | python3 -

      # - name: Install tomlkit
      #   run: pip3 install tomlkit

      # - name: Link Packages in dev branch
      #   run: python3 scripts/link_packages.py

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.POLYWRAP_BUILD_BOT_PAT }}
          push-to-fork: ${{env.RELEASE_FORKS}}/${{github.event.pull_request.base.repo.name}}
          # branch: post-release/origin-${{env.RELEASE_VERSION}}
          # base: origin/dev
          committer: GitHub <noreply@github.com>
          author: ${{env.BUILD_BOT}} <${{env.BUILD_BOT}}@users.noreply.github.com>
          commit-message: "DEV ${{env.RELEASE_VERSION}}"
          title: 'Link packages in dev after (${{env.RELEASE_VERSION}})'
          body: |
            ## Link packages in dev after (${{env.RELEASE_VERSION}})
